### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by mauro-balades** [ReCT-Programming-Language/ReCT-Go-Compiler#5]
Add a license so that doggy people don't steal your code!

**Comment by colsak** [comment]
Doggy people... 🐶

**Comment by WillTheDeveloper** [comment]
![20220203_151323.jpg](https://user-images.githubusercontent.com/78596837/152531434-72f13d80-91ea-4e8d-8e45-691305dd0c2b.jpg)

**Comment by RedCubeDev-ByteSpace** [comment]
put under GNU GPL3 👍

**Comment by mauro-balades** [comment]
MIT?

**Comment by mauro-balades** [comment]
I see that you have added one... Closing.
